import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Header from "../components/elements/Header";
import Footer from "@/components/elements/Footer";
import Main from "../components/layouts/Main";
import TestCarousel from "../components/layouts/Swiper";

export default function Home() {
  return (
    <>
      <Head>
        <title>株式会社ガリバー|トップ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <Main />
        <TestCarousel />
      </main>
      <Footer />
    </>
  );
}
